[package]
name = "average"
version = "0.1.0"
authors = ["nephren"]
edition = "2018"

[features]
parallel = ["rayon"]
default = ["parallel"]

[dependencies]
failure = "0.1.8"
vapoursynth = "0.3.0"
rayon = { version = "1.3.0", optional = true }
half = "1.6.0"

[lib]
crate-type = ["cdylib"]
